server:
  port: 7081

spring:
  application:
    name: reactive-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/demo
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group-id
mongodb:
  database: demo

