server:
  port: 7080

spring:
  application:
    name: reactive-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/demo

mongodb:
  database: demo

#Swagger path
#http://localhost:7080/webjars/swagger-ui/index.html



