server:
  port: 7080

spring:
  application:
    name: reactive-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/demo
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group-id
mongodb:
  database: demo

#Swagger path
#http://localhost:7080/webjars/swagger-ui/index.html
